import { LucideIcon, Smartphone } from "lucide-react";

export interface PortfolioProject {
  title: string;
  description: string;
  image: string;
  type: string;
  icon: LucideIcon;
  technologies: string[];
  features: string[];
  github: string;
  demo: string;
  role: string;
  duration: string;
  category: "mobile" | "web" | "devops";
  platforms?: string;
}

export const portfolioProjects: PortfolioProject[] = [
  {
    title: "Glo Bar — Multi-tenant salon POS",
    description:
      "Multi-tenant salon management POS and ecosystem: customer app for browsing services, booking, and Stripe payments; staff app for services, orders, appointments, payroll, and tips; admin web portal for multiple salons, locations, and configuration.",
    image: "/projects/jtnails.png",
    type: "React Native + Next.js · 2 apps + web",
    icon: Smartphone,
    technologies: [
      "React Native",
      "Next.js",
      "TypeScript",
      "Redux Toolkit",
      "Stripe",
      "Multi-tenant",
      "Push notifications",
    ],
    features: [
      "Customer & staff apps",
      "Stripe payments",
      "Appointments & POS",
      "Payroll & tips",
      "Multi-salon admin",
      "Multi-location",
    ],
    github: "#",
    demo: "#",
    role: "Full-stack mobile developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web",
  },
  {
    title: "Restaurant POS — Full ecosystem",
    description:
      "Full restaurant management suite: waiter, kitchen, main POS, booker, kiosk, and supporting roles. Orders, tables, bookings, stock, and multi-location operations with a central admin web portal.",
    image: "/projects/orbypos.png",
    type: "React Native suite · 5+ apps + web",
    icon: Smartphone,
    technologies: [
      "React Native",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Redux Toolkit",
      "Real-time sync",
      "POS integrations",
    ],
    features: [
      "Role-specific apps",
      "Stock & menu",
      "Bookings & tables",
      "Multi-location",
      "Admin configuration",
      "Kitchen & floor workflows",
    ],
    github: "#",
    demo: "#",
    role: "Full-stack developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web",
  },
  {
    title: "Kisko — Digital signage",
    description:
      "Digital signage platform: upload and schedule media, group devices, and manage subscriptions from a web portal, with players on phones, tablets, and TV form factors.",
    image: "/projects/orbydisplay.png",
    type: "React Native + web control",
    icon: Smartphone,
    technologies: [
      "React Native",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Device grouping",
      "Scheduling",
    ],
    features: [
      "Media upload & schedules",
      "Device groups",
      "Multi-device playback",
      "Subscription model",
      "Centralized portal",
    ],
    github: "#",
    demo: "#",
    role: "Mobile developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web, TV",
  },
  {
    title: "Pixy — AI image & video",
    description:
      "AI creative app: text-to-image and text-to-video with predefined templates and prompts for fast marketing and social content without heavy manual design.",
    image: "/projects/pixsy.png",
    type: "React Native · AI generation",
    icon: Smartphone,
    technologies: [
      "React Native",
      "TypeScript",
      "Redux Toolkit",
      "AI templates",
      "Media pipelines",
    ],
    features: [
      "Text-to-image",
      "Text-to-video",
      "Template library",
      "Generation history",
      "Freemium-ready flows",
    ],
    github: "#",
    demo: "#",
    role: "Mobile developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS",
  },
  {
    title: "Future Soul — Verified matrimonial",
    description:
      "Verified matrimonial platform: profiles, browse and filter, tiered proposals, secure chat, and admin tooling—similar in scope to major regional matchmaking apps.",
    image: "/projects/futuresoul.png",
    type: "React Native + web admin",
    icon: Smartphone,
    technologies: [
      "React Native",
      "TypeScript",
      "Redux Toolkit",
      "Chat",
      "Verification flows",
    ],
    features: [
      "Profile verification",
      "Proposals & tiers",
      "Secure messaging",
      "Subscription model",
      "Web admin",
    ],
    github: "#",
    demo: "#",
    role: "Full-stack developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web",
  },
  {
    title: "Hamsafar — Matchmaking platform",
    description:
      "Matrimonial product with verified profiles, proposals, and chat; emphasis on trust and safety for singles and families, with admin-backed verification.",
    image: "/placeholder.svg",
    type: "React Native + web",
    icon: Smartphone,
    technologies: [
      "React Native",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Real-time chat",
    ],
    features: [
      "Registration & profiles",
      "Proposals",
      "Chat",
      "Verification",
      "Web admin",
    ],
    github: "#",
    demo: "#",
    role: "Mobile developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web",
  },
  {
    title: "Irreecha — Festival management",
    description:
      "Festival management for visitors and organizers: registrations, donations, and moderated content with admin approval so only verified posts go live.",
    image: "/projects/sajamgast.png",
    type: "React Native + React web",
    icon: Smartphone,
    technologies: [
      "React Native",
      "React.js",
      "TypeScript",
      "Redux Toolkit",
      "Content moderation",
    ],
    features: [
      "Visitor & organizer apps",
      "Donations",
      "Verified posts",
      "Admin portal",
      "Attendance insights",
    ],
    github: "#",
    demo: "#",
    role: "Mobile developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web",
  },
  {
    title: "NeighborHold — Parcel holding",
    description:
      "Neighbor-based parcel receiving: consumers request holds; verified neighbors accept or decline; sizing-based payouts and admin-backed identity checks for a trusted local network.",
    image: "/placeholder.svg",
    type: "React Native + Next.js · 2 apps + web",
    icon: Smartphone,
    technologies: [
      "React Native",
      "Next.js",
      "TypeScript",
      "Payments",
      "Verification",
    ],
    features: [
      "Consumer & holder apps",
      "Secure verification",
      "Parcel sizing & fees",
      "Admin review",
      "Trust-first UX",
    ],
    github: "#",
    demo: "#",
    role: "Developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web",
  },
  {
    title: "SAAP — Scam awareness network",
    description:
      "Community scam-awareness app: report and discuss scams, social features (posts, comments, groups), company records, verified publishing, and localized push alerts.",
    image: "/placeholder.svg",
    type: "Nest.js + Next.js + React Native",
    icon: Smartphone,
    technologies: [
      "React Native",
      "Nest.js",
      "Next.js",
      "TypeScript",
      "Push notifications",
    ],
    features: [
      "Verified content",
      "Location-aware alerts",
      "Groups & engagement",
      "Admin portal",
      "Company CRUD",
    ],
    github: "#",
    demo: "#",
    role: "Developer",
    duration: "Live product",
    category: "mobile",
    platforms: "Android, iOS, Web",
  },
  {
    title: "STYLEY — AI lifestyle platform",
    description:
      "Large-scale AI lifestyle product: 100+ generation templates, multi-model chatbot, real-time chat, maps and property exploration, payments, and virtual try-on style experiences. Led a seven-developer mobile track.",
    image: "/projects/styley.png",
    type: "React Native AI platform",
    icon: Smartphone,
    technologies: [
      "React Native",
      "Supabase",
      "TypeScript",
      "Redux Toolkit",
      "Maps",
      "Payments",
    ],
    features: [
      "Template library",
      "AI chat",
      "Real-time messaging",
      "Maps integration",
      "Team leadership",
    ],
    github: "#",
    demo: "#",
    role: "Lead React Native developer",
    duration: "1 year",
    category: "mobile",
    platforms: "Android, iOS",
  },
  {
    title: "Flipsy — Card memory game",
    description:
      "Polished memory game with progressive difficulty, multiple themes, and AdMob monetization—showcasing animation-heavy React Native gameplay.",
    image: "/projects/flipsy.png",
    type: "React Native game",
    icon: Smartphone,
    technologies: [
      "React Native",
      "TypeScript",
      "Redux Toolkit",
      "AdMob",
      "Animations",
    ],
    features: [
      "Difficulty levels",
      "Theme packs",
      "Ad monetization",
      "Score & progression",
    ],
    github: "#",
    demo: "#",
    role: "React Native developer",
    duration: "3 months",
    category: "mobile",
    platforms: "Android, iOS",
  },
  {
    title: "FFC Sports Complex — Events",
    description:
      "Sports complex event and booking flows: facility scheduling, registrations, and operational tooling for staff and visitors on mobile.",
    image: "/projects/ffc.png",
    type: "React Native",
    icon: Smartphone,
    technologies: [
      "React Native",
      "TypeScript",
      "Redux Toolkit",
      "Firebase",
    ],
    features: [
      "Event planning",
      "Facility booking",
      "User registration",
      "Scheduling",
    ],
    github: "#",
    demo: "#",
    role: "React Native developer",
    duration: "5 months",
    category: "mobile",
    platforms: "Android, iOS",
  },
];
